### PR TITLE
Button

### PR DESCRIPTION
**Pull request by Hato6502**
The button device driver

main code: /dev/button/button.c

### CODE REVIEW

**Comment by kuromike0629** [comment]
In order to remove files from repositories.
Use
""git rm [file name]""

**Comment by kuromike0629** [comment]
.hello directory is needed?

**Comment by Hato6502** [comment]
No, I'll remove this directory. 
And...,  "linux dot files"(.*) too.

**Comment by kuromike0629** [comment]
I think you already made new repository and also I'm working to make new organization.
Please wait to merge all source files until new organization and repositories will be created.

**Comment by Hato6502** [comment]
Okay

**Pull request closed without merging**
